
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  FileText,
  BarChart,
  Calendar,
  PieChart,
  Download,
  Filter,
  RefreshCw,
  Plus,
  ChevronRight
} from "lucide-react";
import MainLayout from "@/components/layout/MainLayout";
import { DataTable } from "@/components/ui/data-table";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import ReportGenerator from "@/components/reports/ReportGenerator";

interface Report {
  id: string;
  name: string;
  type: "attendance" | "progress" | "financial" | "custom";
  generatedBy: string;
  dateGenerated: string;
  status: "ready" | "generating" | "error";
  downloads: number;
}

const ReportsDashboard = () => {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState("overview");
  const [showGenerator, setShowGenerator] = useState(false);

  const recentReports: Report[] = [
    {
      id: "r1",
      name: "Weekly Attendance Summary",
      type: "attendance",
      generatedBy: "John Smith",
      dateGenerated: "2023-09-15",
      status: "ready",
      downloads: 23
    },
    {
      id: "r2",
      name: "Monthly Progress Report",
      type: "progress",
      generatedBy: "Sarah Johnson",
      dateGenerated: "2023-09-10",
      status: "ready",
      downloads: 41
    },
    {
      id: "r3",
      name: "Q3 Financial Summary",
      type: "financial",
      generatedBy: "Michael Davies",
      dateGenerated: "2023-09-05",
      status: "ready",
      downloads: 17
    },
    {
      id: "r4",
      name: "Custom Parent Survey Results",
      type: "custom",
      generatedBy: "Emma Wilson",
      dateGenerated: "2023-09-01",
      status: "generating",
      downloads: 0
    }
  ];

  const reportColumns = [
    {
      key: "name" as keyof Report,
      header: "Report Name",
      sortable: true,
      render: (value: string, report: Report) => (
        <div className="flex items-center">
          <div className="mr-2">
            {report.type === "attendance" && <FileText size={18} className="text-blue-500" />}
            {report.type === "progress" && <BarChart size={18} className="text-green-500" />}
            {report.type === "financial" && <PieChart size={18} className="text-purple-500" />}
            {report.type === "custom" && <FileText size={18} className="text-orange-500" />}
          </div>
          <div>
            <div className="font-medium">{value}</div>
            <div className="text-xs text-gray-500">Type: {report.type.charAt(0).toUpperCase() + report.type.slice(1)}</div>
          </div>
        </div>
      )
    },
    {
      key: "generatedBy" as keyof Report,
      header: "Generated By",
      sortable: true
    },
    {
      key: "dateGenerated" as keyof Report,
      header: "Date",
      sortable: true,
      render: (value: string) => new Date(value).toLocaleDateString()
    },
    {
      key: "status" as keyof Report,
      header: "Status",
      sortable: true,
      render: (value: string) => (
        <div className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
          value === "ready" ? "bg-green-100 text-green-800" :
          value === "generating" ? "bg-yellow-100 text-yellow-800" :
          "bg-red-100 text-red-800"
        }`}>
          {value === "generating" && <RefreshCw size={12} className="mr-1 animate-spin" />}
          {value.charAt(0).toUpperCase() + value.slice(1)}
        </div>
      )
    },
    {
      key: "downloads" as keyof Report,
      header: "Downloads",
      sortable: true
    }
  ];

  // Chart data for the overview tab
  const reportMetrics = [
    { id: 1, title: "Total Reports", value: 156, change: "+12%", icon: <FileText className="text-blue-500" /> },
    { id: 2, title: "Generated This Month", value: 24, change: "+8%", icon: <Calendar className="text-green-500" /> },
    { id: 3, title: "Most Downloaded", value: "Attendance", change: "41 downloads", icon: <Download className="text-purple-500" /> },
    { id: 4, title: "Report Types", value: "4", change: "Active", icon: <PieChart className="text-orange-500" /> }
  ];

  // Report categories for the reports tab
  const reportCategories = [
    { id: 1, name: "Attendance Reports", description: "Track student attendance and check-in/check-out patterns", count: 42 },
    { id: 2, name: "Progress Reports", description: "Monitor student achievements and development over time", count: 37 },
    { id: 3, name: "Financial Reports", description: "Analyze financial data, fees, and payments", count: 28 },
    { id: 4, name: "Custom Reports", description: "User-defined reports with specific parameters", count: 49 }
  ];

  return (
    <MainLayout>
      <div className="flex flex-col gap-6">
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-bold tracking-tight">Reports Dashboard</h1>
            <p className="text-muted-foreground">Manage and generate reports for your organization</p>
          </div>
          <Button 
            className="bg-purple-600 hover:bg-purple-700" 
            onClick={() => setShowGenerator(true)}
          >
            <Plus size={16} className="mr-2" /> Generate New Report
          </Button>
        </div>

        {showGenerator ? (
          <ReportGenerator onClose={() => setShowGenerator(false)} />
        ) : (
          <Tabs defaultValue="overview" value={activeTab} onValueChange={setActiveTab} className="w-full">
            <TabsList className="mb-4">
              <TabsTrigger value="overview">Overview</TabsTrigger>
              <TabsTrigger value="reports">Report Categories</TabsTrigger>
              <TabsTrigger value="recent">Recent Reports</TabsTrigger>
            </TabsList>
            
            <TabsContent value="overview" className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                {reportMetrics.map(metric => (
                  <Card key={metric.id} className="p-4">
                    <div className="flex justify-between">
                      <div>
                        <p className="text-sm font-medium text-gray-500">{metric.title}</p>
                        <h3 className="text-2xl font-bold mt-1">{metric.value}</h3>
                        <p className="text-xs text-green-600 mt-1">{metric.change}</p>
                      </div>
                      <div className="h-12 w-12 rounded-full bg-gray-100 flex items-center justify-center">
                        {metric.icon}
                      </div>
                    </div>
                  </Card>
                ))}
              </div>
              
              <Card className="p-6">
                <h3 className="text-lg font-medium mb-4">Recent Reports</h3>
                <DataTable
                  columns={reportColumns}
                  data={recentReports.slice(0, 5)}
                  keyExtractor={(item) => item.id}
                  searchable={false}
                  onRowClick={(report) => {
                    // Handle report click
                    console.log("Clicked on report:", report);
                  }}
                />
                <div className="mt-4 flex justify-center">
                  <Button variant="outline" onClick={() => setActiveTab("recent")}>
                    View All Reports <ChevronRight size={16} className="ml-1" />
                  </Button>
                </div>
              </Card>
            </TabsContent>
            
            <TabsContent value="reports" className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {reportCategories.map(category => (
                  <Card key={category.id} className="p-4 hover:shadow-md transition-shadow cursor-pointer">
                    <div className="flex justify-between items-center">
                      <div>
                        <h3 className="text-lg font-medium">{category.name}</h3>
                        <p className="text-sm text-gray-500 mt-1">{category.description}</p>
                        <div className="mt-2 text-xs text-gray-600">{category.count} reports available</div>
                      </div>
                      <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                        <ChevronRight size={18} />
                      </Button>
                    </div>
                  </Card>
                ))}
              </div>
              
              <div className="mt-6">
                <Button 
                  className="bg-purple-600 hover:bg-purple-700 w-full" 
                  onClick={() => setShowGenerator(true)}
                >
                  <Plus size={16} className="mr-2" /> Create Custom Report
                </Button>
              </div>
            </TabsContent>
            
            <TabsContent value="recent">
              <Card className="p-6">
                <div className="flex justify-between items-center mb-4">
                  <h3 className="text-lg font-medium">All Reports</h3>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm">
                      <Filter size={14} className="mr-1" /> Filter
                    </Button>
                    <Button variant="outline" size="sm">
                      <RefreshCw size={14} className="mr-1" /> Refresh
                    </Button>
                  </div>
                </div>
                
                <DataTable
                  columns={reportColumns}
                  data={recentReports}
                  keyExtractor={(item) => item.id}
                  searchable={true}
                  searchPlaceholder="Search reports..."
                  onRowClick={(report) => {
                    // Handle report click
                    console.log("Clicked on report:", report);
                  }}
                />
              </Card>
            </TabsContent>
          </Tabs>
        )}
      </div>
    </MainLayout>
  );
};

export default ReportsDashboard;
